# Introduction to Python for Environmental Science - Tabular Data
* Affiliation: UK Met Office
* History: 1.0
* Last update: 17-05-2023
* © British Crown Copyright 2017-2023, Met Office. Please see LICENSE.md for license details.


![JCEEI logo](../jceei_logo.png)

## Objectives of this session

- Awareness of the difference between tabular and gridded datasets
- Understand how to load and manipulate data using NumPy
- Understand of how to load and manipulate data using pandas 
- How to calculate summary statistics in both NumPy and pandas 

## Key data types
There are two core types of data that are commonly used in Environmental Science:

### Tabular Data
This is data in rows and columns, as you would expect to see in a spreadsheet.
 - Each row represents a data point e.g. e.g. each employee in a payroll system; each measurement time in a weather observation system
 - Each column represent a feature of the data point e.g. name, employee ID, department, salary in a payroll system; temperature, wind, sunshine in a weather observation system

### Gridded Data
A multi-dimensional array of data, reperesenting a regular grid of measurements.
 - This might be the output of a weather forecast model over the UK.
 - Dimensions could be latitude, longitude and time.

This notebook will focus on tabular data, with gridded datasets and python tools for loading and working with gridded data being covered later in the session. 

# Tabular data

## NumPy

NumPy is the fundamental package for scientific computing with Python. Its primary purpose is to provide a powerful N-dimensional array object. Here will mainly focus on it's application to two dimensional data.

### What is NumPy?

NumPy: 'Numerical Python'

- Open source Python library
- A library of fast, precompiled functions 
- Efficient computation with multi-dimensional arrays

To begin with let's import NumPy and check the version.

In [1]:
# NumPy is often imported as np 
import numpy as np
print(np.__version__)

1.23.3


### Documentation 

Here is a link to the NumPy documentation for v1.23: https://numpy.org/doc/1.23/index.html

### Creating arrays in NumPy

NumPy provides many different ways to create arrays. These are listed in the documentation at: https://numpy.org/doc/stable/user/basics.creation.html

In [2]:
vals = [0, 1, 2, 3, 4, 5, 6, 7, 8]
vals_arr = np.array(vals)
vals_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

NumPy arrays are containers of elements of the same *type* e.g. only integers. The type of an array can be determined with the attribute `dtype` and changed with the attribute `astype`

In [3]:
vals_arr.dtype

dtype('int64')

In [4]:
vals_arr.astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

We can create an array using `arange`, which returns a numpy array containing evenly spaced values within a given interval. 

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

### Indexing arrays

You can index NumPy arrays in the same way as other Python objects, by using square brackets `[]`. This means we can index to retrieve a single element, multiple consecutive elements, or a more complex sequence:

In [8]:
arr = np.arange(1,7)
print(arr)

[1 2 3 4 5 6]


Indexing counts from zero

In [9]:
print(f"arr[2] = {arr[2]}") 

arr[2] = 3


Starting and stopping index, up to and not include the stopping index

In [10]:
print(f"arr[2:5] = {arr[2:5]}") 

arr[2:5] = [3 4 5]


Start at first element, stop at last element, take every other element

In [11]:
print(f"arr[::2] = {arr[::2]}")

arr[::2] = [1 3 5]


We can also index conditionally, based on the data in the array. 

You can pass in an array of True and False values (a boolean array), or, more commonly, a condition that returns a boolean array.

First of all, we create our condition and assign the output to the argument bools

In [12]:
bools = arr % 2 == 0  # % operator give the remainder of the devision, when '% 2' the answer will always be 1 or 0
bools

array([False,  True, False,  True, False,  True])

In [13]:
arr[bools]

array([2, 4, 6])

### Multi-dimensional arrays

The multidimensional array object is at the core of all of NumPy's functionality. Let's explore this object some more. 

In [14]:
print(arr)

[1 2 3 4 5 6]


We will use reshape to create our 2 dimensional array from our original array.

In [15]:
arr_2d = arr.reshape(2,3)
print(arr_2d)

[[1 2 3]
 [4 5 6]]


Lets explore some of the properties of this 2 dimensional array

In [16]:
print("Array shape:", arr_2d.shape)
print("Array element dtype:", arr_2d.dtype)
print('Number of dimensions in arr:', arr_2d.ndim)
print('Number of elements in the array:', arr_2d.size)

Array shape: (2, 3)
Array element dtype: int64
Number of dimensions in arr: 2
Number of elements in the array: 6


We can also transpose the array

In [17]:
print('Transposed array:')
print(arr_2d.T)
print('Shape of transposed array:', arr_2d.T.shape)

Transposed array:
[[1 4]
 [2 5]
 [3 6]]
Shape of transposed array: (3, 2)


### Arthimetic and Broadcasting

You can use NumPy to perform arithmetic operations between two arrays in an element-by-element fashion. this applies for all of the basic Python mathematical operators (i.e. `+`, `-`, `*`, `/`, `//`, `%`)

In [18]:
arr1 = np.arange(5)
arr2 = np.arange(5)
print('Array 1:', arr1)
print('Array 2:', arr2)

Array 1: [0 1 2 3 4]
Array 2: [0 1 2 3 4]


In [19]:
print(f'{arr1} + {arr2} = {arr1 + arr2}')

[0 1 2 3 4] + [0 1 2 3 4] = [0 2 4 6 8]


In [20]:
print(f'{arr1} - {arr2} = {arr1 - arr2}')

[0 1 2 3 4] - [0 1 2 3 4] = [0 0 0 0 0]


In [21]:
print(f'{arr1} * {arr2} = {arr1 * arr2}')

[0 1 2 3 4] * [0 1 2 3 4] = [ 0  1  4  9 16]


### Broadcasting 

There are times when you need to perform calculations between NumPy arrays of different sizes.

For example, suppose you have maximum temperatures from each of three recording stations, recorded on two separate days.

In [22]:
daily_records = np.array([[12, 14, 11], [11, 12, 15]])

print('raw data:')
print(daily_records)

raw data:
[[12 14 11]
 [11 12 15]]


Each station is known to overstate the maximum recorded temperature by a different known constant value. You wish to subtract the appropriate offset from each station's values.

You can do that like this:

In [23]:
offset = np.array([2, 1, 4])

corrected_records = daily_records - offset

print('corrected values:')
print(corrected_records)

corrected values:
[[10 13  7]
 [ 9 11 11]]


NumPy allows you to do this easily using a powerful piece of functionality called **broadcasting**.

Broadcasting is a way of treating the arrays ***as if*** they had the same dimensions, and thus have elements all corresponding.  It is then easy to perform the calculation, element-wise.  
It does this by matching dimensions in one array to the other where possible, and using repeated values where there is no corresponding dimension in the other array.

### Rules of Broadcasting 

Broadcasting applies these three rules:

1.    If the two arrays differ in their number of dimensions, the shape of the array with fewer dimensions is padded with ones on its leading (left) side.

1.    If the shape of the two arrays does not match in any dimension, either array with shape equal to 1 in a given dimension is stretched to match the other shape.

1.    If in any dimension the sizes disagree and neither has shape equal to 1, an error is raised.

### Loading data with NumPy

As well as creating arrays in NumPy, we can also load data into NumPy arrays from files. NumPy supports loading data from text files e.g. txt or csv file formats, which are commonly used to store tabular datasets.  

In [24]:
weather_arr = np.loadtxt('weather.csv', delimiter=',', skiprows=1)

In [25]:
print(weather_arr)

[[1.4e+03 2.1e+01 2.0e+00 0.0e+00]
 [1.5e+03 2.4e+01 5.0e+00 0.0e+00]
 [1.6e+03 2.0e+01 1.5e+01 1.0e+00]
 [1.7e+03 2.2e+01 5.0e+00 1.5e+01]
 [1.8e+03 2.1e+01 1.0e+00 0.0e+00]]


In [26]:
print('Array shape:', weather_arr.shape)

Array shape: (5, 4)


We are able to select data in different rows and columns in this array using indexing. So for example, we can select the first two rows of our dataset:

In [27]:
weather_arr[0:2]

array([[1400.,   21.,    2.,    0.],
       [1500.,   24.,    5.,    0.]])

However, as there are no labels for the data, if we want to select the time column for example, we need to refer back to the original dataset and check which column time data is in before indexing.

In [28]:
weather_arr[:, 0]

array([1400., 1500., 1600., 1700., 1800.])

### Concatenation - combining multiple arrays

We can combine multiple NumPy arrays using concatentation. The arrays must have the same shape except in the dimension corresponding to the axis along which the arrays are joined.

For example, if we compare the shape of `weather_arr` and `weather_arr2`, they both have 5 rows, but `weather_arr` has 4 columns and `weather_arr2` only has 3. So if we try to concatenate these two arrays based on columns (in NumPy terms with axis=0, this is the default), we will get an error as there is a different number of columns (Exercise: give this a try!). However, we can concatenate these two based on rows (axis=1), as both arrays have 5 rows. 

In [29]:
weather_arr.shape

(5, 4)

In [30]:
weather_arr2 = np.loadtxt('weather2.csv', delimiter=',', skiprows=1)
weather_arr2.shape

(5, 3)

In [31]:
combined_arr = np.concatenate([weather_arr, weather_arr2], axis=1)
combined_arr

array([[1.400e+03, 2.100e+01, 2.000e+00, 0.000e+00, 1.400e+03, 1.700e+01,
        1.007e+03],
       [1.500e+03, 2.400e+01, 5.000e+00, 0.000e+00, 1.500e+03, 1.900e+01,
        1.005e+03],
       [1.600e+03, 2.000e+01, 1.500e+01, 1.000e+00, 1.600e+03, 2.000e+01,
        1.003e+03],
       [1.700e+03, 2.200e+01, 5.000e+00, 1.500e+01, 1.700e+03, 1.800e+01,
        1.006e+03],
       [1.800e+03, 2.100e+01, 1.000e+00, 0.000e+00, 1.800e+03, 1.700e+01,
        1.008e+03]])

In [32]:
combined_arr.shape

(5, 7)

Note that the time column, which was the same in both datasets, has been duplicated.

### Calculating summary statistics 

NumPy arrays support many common statistical calculations. For a list of common operations, see: https://numpy.org/doc/stable/reference/routines.statistics.html.

The simplest operations consist of calculating a single statistical value from an array of numbers,e.g. a mean value, a variance or a minimum.

Let's calculate these for the temperature column in our dataset:

In [33]:
temperature = weather_arr[:, 1]
temperature

array([21., 24., 20., 22., 21.])

In [34]:
print('Minimum temperature = ', np.min(temperature))
print('Maximum temperature = ', np.max(temperature))

Minimum temperature =  20.0
Maximum temperature =  24.0


In [35]:
print('Mean temperature = ', np.mean(temperature))
print('Median temperature = ', np.median(temperature))

Mean temperature =  21.6
Median temperature =  21.0


In [36]:
print('Standard deviation = ', np.std(temperature))
print('Variance = ', np.var(temperature))

Standard deviation =  1.3564659966250536
Variance =  1.8399999999999999


Used without any further arguments, statistical functions simply reduce the whole array to a single value.  In practice, however, we very often want to calculate statistics over only *some* of the dimensions.

The most common requirement is to calculate a statistic along a single array dimension, while leaving all the other dimensions intact.   This is referred to as "collapsing" or "reducing" the chosen dimension.

This is done by adding an "axis" keyword specifying which dimension, such as `np.min(data, axis=1)`. 

In [37]:
print('Minimum value in each column = ', np.min(weather_arr, axis=0))

Minimum value in each column =  [1.4e+03 2.0e+01 1.0e+00 0.0e+00]


## Pandas

While NumPy is a useful tool, we have already seen a couple of things that make data analysis more challenging e.g. not explicitly having metadata (column names) for our dataset when we load data from a csv file, meaning it can be difficult to keep track of what the values represent. 

Pandas is another open source Python library, which is commonly used for data manipulation and analysis of tabular datasets.

Let's start by importing pandas:

In [38]:
# Pandas is often imported as pd 
import pandas as pd
print(pd.__version__)

1.5.0


### Documentation

Here is a link to the Pandas documentation for v1.5: https://pandas.pydata.org/pandas-docs/version/1.5/user_guide/index.html#user-guide

### Loading tabular data into a pandas dataframe

A DataFrame is the standard object for working with tabular data in Python. This provides an intuitive way to access and manipulate data.

In [39]:
weather_df = pd.read_csv('weather.csv')
print(type(weather_df))
weather_df

<class 'pandas.core.frame.DataFrame'>


time  temperature  wind  rain
0  1400           21     2     0
1  1500           24     5     0
2  1600           20    15     1
3  1700           22     5    15
4  1800           21     1     0

Now that we have loaded a tabular data into Pandas, we can apply some common operations used for data analysis. Hopefully you'll see that these are more intuitive, and often require less code than when implemented manually.

Perhaps the most important advantage of using a library such as Pandas is that it has been optimised for large tabular datasets, and so will usually perform better than manual python code.

### Indexing and subsetting data

We might start by selecting data from a particular column of our dataset. Pandas allows us to select data from a column based on the name of the column, meaning we don't have to keep refering back to the original data file (as we did with NumPy). 

In [40]:
weather_df['temperature']

0    21
1    24
2    20
3    22
4    21
Name: temperature, dtype: int64

It is also possible to select multiple columns, which is simple done by providing the column names to be selected within a list, like so:

In [41]:
weather_df[['temperature', 'rain']]

temperature  rain
0           21     0
1           24     0
2           20     1
3           22    15
4           21     0

Warning, traditional indexing does not work with Pandas DataFrame. As you see below, we get an error when we try to select the first row of the dataframe using indexing. 

Instead, we use the `.loc` and `.iloc` functionality in pandas, `.iloc` selects a row based on the index and `.loc` select a row based on the index value. 

Note: these two will return the same result if the default index is being used.

In [42]:
weather_df[0]

KeyError: 0

In [43]:
weather_df.iloc[0]

time           1400
temperature      21
wind              2
rain              0
Name: 0, dtype: int64

Similair to conditional indexing that we discussed earlier, we can select rows of a DataFrame based on the values in a certain column. 

Let's select rows in our DataFrame, where the value in the temperature column is greater than 21

In [44]:
weather_df[weather_df['temperature']>21]

time  temperature  wind  rain
1  1500           24     5     0
3  1700           22     5    15

In [45]:
weather_df

time  temperature  wind  rain
0  1400           21     2     0
1  1500           24     5     0
2  1600           20    15     1
3  1700           22     5    15
4  1800           21     1     0

Exercise: Try selecting the subset of our data when wind is greater than 4

In [ ]:
# Add your exercise solution here

### Combining dataframes

Pandas has some nice documentation explaining the different ways you can combine a dataset: https://pandas.pydata.org/docs/user_guide/merging.html

In [46]:
weather_df2 = pd.read_csv('weather2.csv')
weather_df2

time  dewpoint  pressure
0  1400        17      1007
1  1500        19      1005
2  1600        20      1003
3  1700        18      1006
4  1800        17      1008

As with NumPy, pandas has functionality to concatenate multiple DataFrame. The advantage of pandas is that rather than just returning an error when the shape of two arrays is different, it will try to handle and where necessary fill any missing data with `NaN` values ('Not a Number'). 

In [47]:
pd.concat([weather_df, weather_df2])

time  temperature  wind  rain  dewpoint  pressure
0  1400         21.0   2.0   0.0       NaN       NaN
1  1500         24.0   5.0   0.0       NaN       NaN
2  1600         20.0  15.0   1.0       NaN       NaN
3  1700         22.0   5.0  15.0       NaN       NaN
4  1800         21.0   1.0   0.0       NaN       NaN
0  1400          NaN   NaN   NaN      17.0    1007.0
1  1500          NaN   NaN   NaN      19.0    1005.0
2  1600          NaN   NaN   NaN      20.0    1003.0
3  1700          NaN   NaN   NaN      18.0    1006.0
4  1800          NaN   NaN   NaN      17.0    1008.0

This however, is still not doing exactly what we want. We want the returned DataFrame to contain our five timesteps with columns for the five different weather variables. 

As with NumPy, we can define the axis to join over, which gets us close to what we want, but as we had before with NumPy, the time column in our DataFrame is duplicated, which we don't want. 

In [48]:
pd.concat([weather_df, weather_df2], axis=1)

time  temperature  wind  rain  time  dewpoint  pressure
0  1400           21     2     0  1400        17      1007
1  1500           24     5     0  1500        19      1005
2  1600           20    15     1  1600        20      1003
3  1700           22     5    15  1700        18      1006
4  1800           21     1     0  1800        17      1008

Pandas offers other ways to combine datasets. One of these options is to `merge`, which allows us to merge DataFrame objects with a database-style join. We can either select to join based on certain columns by name, or using the DataFrame index. 

Here we are merging `weather_df` and `weather_df2` based on the 'time' columns.

In [49]:
combined_weather_df = pd.merge(weather_df, weather_df2, right_on='time', left_on='time')
combined_weather_df

time  temperature  wind  rain  dewpoint  pressure
0  1400           21     2     0        17      1007
1  1500           24     5     0        19      1005
2  1600           20    15     1        20      1003
3  1700           22     5    15        18      1006
4  1800           21     1     0        17      1008

### Summary statistics

Pandas has functionality to calculate all of the summary statistics that we calculated with NumPy directly from the pandas DataFrame.

Let's calculate some summary statistics for the temperature column:

In [50]:
temperature = combined_weather_df['temperature']

In [51]:
print('Minimum temperature = ', temperature.min())
print('Maximum temperature = ', temperature.max())

Minimum temperature =  20
Maximum temperature =  24


In [52]:
print('Mean temperature = ', temperature.mean())
print('Median temperature = ', temperature.median())

Mean temperature =  21.6
Median temperature =  21.0


In [53]:
print('Standard deviation = ', temperature.std())
print('Variance = ', temperature.var())

Standard deviation =  1.51657508881031
Variance =  2.3


We can also calculate statistics for all columns at once by applying the functions to the DataFrame. For example, we can calculate the mean value for every column. 

In [54]:
combined_weather_df.mean()

time           1600.0
temperature      21.6
wind              5.6
rain              3.2
dewpoint         18.2
pressure       1005.8
dtype: float64

Finally, the pandas `describe` function is useful for getting an overview of the entire dataset, calculating a number of useful summary statistics at once including the mean, standard deviation and interquartile range of the data in the DataFrame. 

In [55]:
combined_weather_df.describe()

time  temperature       wind       rain  dewpoint     pressure
count     5.000000     5.000000   5.000000   5.000000   5.00000     5.000000
mean   1600.000000    21.600000   5.600000   3.200000  18.20000  1005.800000
std     158.113883     1.516575   5.549775   6.610598   1.30384     1.923538
min    1400.000000    20.000000   1.000000   0.000000  17.00000  1003.000000
25%    1500.000000    21.000000   2.000000   0.000000  17.00000  1005.000000
50%    1600.000000    21.000000   5.000000   0.000000  18.00000  1006.000000
75%    1700.000000    22.000000   5.000000   1.000000  19.00000  1007.000000
max    1800.000000    24.000000  15.000000  15.000000  20.00000  1008.000000

### Advantages of pandas
Having looked at how one can use Pandas to handle data, what are the advantages of using this third-party library over writing code in python yourself to do the same operations?
- You spend less time writing boilerplate code and more tieme focusing on what is unique to your data or problem
- The code in pandas has been written and optimised by performance specialists and will certainly be more efficient than a first attempt at the same operation in python
- Coding using the pandas interface opens the possibility of working easily and interchangeably with other libraries such as dask.

## Other useful material

- SciPy lectures for NumPy: http://scipy-lectures.org/intro/numpy/index.html
- Pandas tutorials: https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html